<?php

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__ . '/..');

$dotenv->load();

function add_common_headers() {
  header('Access-Control-Allow-Methods: GET');
  header('Access-Control-Allow-Origin: *');
  header('Last-Modified: ' . gmdate('D, d M Y H:i:s') . ' GMT');
  header('Content-Language: en-US');
  header('Cache-Control: public, max-age=0, s-maxage=300', FALSE);
}

function json($data) {
  add_common_headers();
  header('Content-Type: application/json');
  echo json_encode($data), PHP_EOL;
}

function render($args) {

  global $router;

  add_common_headers();

  header('Content-Type: text/html; charset=utf-8');

  $template = $args['template'];

  $data = $args['data'];

  $data['currentUri'] = $router->getCurrentUri();

  // Specify our Twig templates location.
  $loader = new Twig\Loader\FilesystemLoader(__DIR__ . '/../templates');

  // Instantiate our Twig.
  $twig = new Twig\Environment($loader);

  $twig->addGlobal('ga', $_ENV['GA']);

  $twig->addGlobal('appRoot', $_ENV['APP_ROOT']);

  $twig->addGlobal('ga_ua', $_ENV['GAUA']);

  $twig->addGlobal('site_name', 'NYU Libraries');

  $twig->addGlobal('bobcat_url', $_ENV['bobcat_url']);

  echo $twig->render($template, $data);

}

function utilities_lang($langCode) {
  $language_codes = [
    'en' => 'English',
    'aa' => 'Afar',
    'ab' => 'Abkhazian',
    'af' => 'Afrikaans',
    'am' => 'Amharic',
    'ar' => 'Arabic',
    'as' => 'Assamese',
    'ay' => 'Aymara',
    'az' => 'Azerbaijani',
    'ba' => 'Bashkir',
    'be' => 'Byelorussian',
    'bg' => 'Bulgarian',
    'bh' => 'Bihari',
    'bi' => 'Bislama',
    'bn' => 'Bengali/Bangla',
    'bo' => 'Tibetan',
    'br' => 'Breton',
    'ca' => 'Catalan',
    'co' => 'Corsican',
    'cs' => 'Czech',
    'cy' => 'Welsh',
    'da' => 'Danish',
    'de' => 'German',
    'dz' => 'Bhutani',
    'el' => 'Greek',
    'eo' => 'Esperanto',
    'es' => 'Spanish',
    'et' => 'Estonian',
    'eu' => 'Basque',
    'fa' => 'Persian',
    'fi' => 'Finnish',
    'fj' => 'Fiji',
    'fo' => 'Faeroese',
    'fr' => 'French',
    'fy' => 'Frisian',
    'ga' => 'Irish',
    'gd' => 'Scots/Gaelic',
    'gl' => 'Galician',
    'gn' => 'Guarani',
    'gu' => 'Gujarati',
    'ha' => 'Hausa',
    'hi' => 'Hindi',
    'hr' => 'Croatian',
    'hu' => 'Hungarian',
    'hy' => 'Armenian',
    'ia' => 'Interlingua',
    'ie' => 'Interlingue',
    'ik' => 'Inupiak',
    'in' => 'Indonesian',
    'is' => 'Icelandic',
    'it' => 'Italian',
    'iw' => 'Hebrew',
    'ja' => 'Japanese',
    'ji' => 'Yiddish',
    'jw' => 'Javanese',
    'ka' => 'Georgian',
    'kk' => 'Kazakh',
    'kl' => 'Greenlandic',
    'km' => 'Cambodian',
    'kn' => 'Kannada',
    'ko' => 'Korean',
    'ks' => 'Kashmiri',
    'ku' => 'Kurdish',
    'ky' => 'Kirghiz',
    'la' => 'Latin',
    'ln' => 'Lingala',
    'lo' => 'Laothian',
    'lt' => 'Lithuanian',
    'lv' => 'Latvian/Lettish',
    'mg' => 'Malagasy',
    'mi' => 'Maori',
    'mk' => 'Macedonian',
    'ml' => 'Malayalam',
    'mn' => 'Mongolian',
    'mo' => 'Moldavian',
    'mr' => 'Marathi',
    'ms' => 'Malay',
    'mt' => 'Maltese',
    'my' => 'Burmese',
    'na' => 'Nauru',
    'ne' => 'Nepali',
    'nl' => 'Dutch',
    'no' => 'Norwegian',
    'oc' => 'Occitan',
    'om' => '(Afan)/Oromoor/Oriya',
    'pa' => 'Punjabi',
    'pl' => 'Polish',
    'ps' => 'Pashto/Pushto',
    'pt' => 'Portuguese',
    'qu' => 'Quechua',
    'rm' => 'Rhaeto-Romance',
    'rn' => 'Kirundi',
    'ro' => 'Romanian',
    'ru' => 'Russian',
    'rw' => 'Kinyarwanda',
    'sa' => 'Sanskrit',
    'sd' => 'Sindhi',
    'sg' => 'Sangro',
    'sh' => 'Serbo-Croatian',
    'si' => 'Singhalese',
    'sk' => 'Slovak',
    'sl' => 'Slovenian',
    'sm' => 'Samoan',
    'sn' => 'Shona',
    'so' => 'Somali',
    'sq' => 'Albanian',
    'sr' => 'Serbian',
    'ss' => 'Siswati',
    'st' => 'Sesotho',
    'su' => 'Sundanese',
    'sv' => 'Swedish',
    'sw' => 'Swahili',
    'ta' => 'Tamil',
    'te' => 'Tegulu',
    'tg' => 'Tajik',
    'th' => 'Thai',
    'ti' => 'Tigrinya',
    'tk' => 'Turkmen',
    'tl' => 'Tagalog',
    'tn' => 'Setswana',
    'to' => 'Tonga',
    'tr' => 'Turkish',
    'ts' => 'Tsonga',
    'tt' => 'Tatar',
    'tw' => 'Twi',
    'uk' => 'Ukrainian',
    'ur' => 'Urdu',
    'uz' => 'Uzbek',
    'vi' => 'Vietnamese',
    'vo' => 'Volapuk',
    'wo' => 'Wolof',
    'xh' => 'Xhosa',
    'yo' => 'Yoruba',
    'zh' => 'Chinese',
    'zu' => 'Zulu',
    // @link https://jira.nyu.edu/jira/browse/DLTSHIDVL-68
    // @link https://en.wikipedia.org/wiki/ISO_639-3
    // @link https://iso639-3.sil.org/code/zxx
    'zxx' => 'No linguistic content, Not applicable',
  ];
  if (empty($langCode) || !array_key_exists($langCode, $language_codes)) {
    $langCode = 'en';
  }
  return $language_codes[$langCode];
}

// This is MAP from ISO 639-1 to ISO 639-2/B as described in the standard
// http://www.loc.gov/standards/iso639-2/php/code_list.php
function map_language_code($lang = 'eng') {
  $map = [
    "aar" => "aa",
    "abk" => "ab",
    "afr" => "af",
    "aka" => "ak",
    "alb" => "sq",
    "amh" => "am",
    "ara" => "ar",
    "arg" => "an",
    "arm" => "hy",
    "asm" => "as",
    "ava" => "av",
    "ave" => "ae",
    "aym" => "ay",
    "aze" => "az",
    "bak" => "ba",
    "bam" => "bm",
    "baq" => "eu",
    "bel" => "be",
    "ben" => "bn",
    "bih" => "bh",
    "bis" => "bi",
    "bos" => "bs",
    "bre" => "br",
    "bul" => "bg",
    "bur" => "my",
    "cat" => "ca",
    "cha" => "ch",
    "che" => "ce",
    "chi" => "zh",
    "chu" => "cu",
    "chv" => "cv",
    "cor" => "kw",
    "cos" => "co",
    "cre" => "cr",
    "cze" => "cs",
    "dan" => "da",
    "div" => "dv",
    "dut" => "nl",
    "dzo" => "dz",
    "eng" => "en",
    "epo" => "eo",
    "est" => "et",
    "ewe" => "ee",
    "fao" => "fo",
    "fij" => "fj",
    "fin" => "fi",
    "fre" => "fr",
    "fry" => "fy",
    "ful" => "ff",
    "geo" => "ka",
    "ger" => "de",
    "gla" => "gd",
    "gle" => "ga",
    "glg" => "gl",
    "glv" => "gv",
    "gre" => "el",
    "grn" => "gn",
    "guj" => "gu",
    "hat" => "ht",
    "hau" => "ha",
    "heb" => "he",
    "her" => "hz",
    "hin" => "hi",
    "hmo" => "ho",
    "hrv" => "hr",
    "hun" => "hu",
    "ibo" => "ig",
    "ice" => "is",
    "ido" => "io",
    "iii" => "ii",
    "iku" => "iu",
    "ile" => "ie",
    "ina" => "ia",
    "ind" => "id",
    "ipk" => "ik",
    "ita" => "it",
    "jav" => "jv",
    "jpn" => "ja",
    "kal" => "kl",
    "kan" => "kn",
    "kas" => "ks",
    "kau" => "kr",
    "kaz" => "kk",
    "khm" => "km",
    "kik" => "ki",
    "kin" => "rw",
    "kir" => "ky",
    "kom" => "kv",
    "kon" => "kg",
    "kor" => "ko",
    "kua" => "kj",
    "kur" => "ku",
    "lao" => "lo",
    "lat" => "la",
    "lav" => "lv",
    "lim" => "li",
    "lin" => "ln",
    "lit" => "lt",
    "ltz" => "lb",
    "lub" => "lu",
    "lug" => "lg",
    "mac" => "mk",
    "mah" => "mh",
    "mal" => "ml",
    "mao" => "mi",
    "mar" => "mr",
    "may" => "ms",
    "mlg" => "mg",
    "mlt" => "mt",
    "mon" => "mn",
    "nau" => "na",
    "nav" => "nv",
    "nbl" => "nr",
    "nde" => "nd",
    "ndo" => "ng",
    "nep" => "ne",
    "nno" => "nn",
    "nob" => "nb",
    "nor" => "no",
    "nya" => "ny",
    "oci" => "oc",
    "oji" => "oj",
    "ori" => "or",
    "orm" => "om",
    "oss" => "os",
    "pan" => "pa",
    "per" => "fa",
    "pli" => "pi",
    "pol" => "pl",
    "por" => "pt",
    "pus" => "ps",
    "que" => "qu",
    "roh" => "rm",
    "rum" => "ro",
    "run" => "rn",
    "rus" => "ru",
    "sag" => "sg",
    "san" => "sa",
    "sin" => "si",
    "slo" => "sk",
    "slv" => "sl",
    "sme" => "se",
    "smo" => "sm",
    "sna" => "sn",
    "snd" => "sd",
    "som" => "so",
    "sot" => "st",
    "spa" => "es",
    "srd" => "sc",
    "srp" => "sr",
    "ssw" => "ss",
    "sun" => "su",
    "swa" => "sw",
    "swe" => "sv",
    "tah" => "ty",
    "tam" => "ta",
    "tat" => "tt",
    "tel" => "te",
    "tgk" => "tg",
    "tgl" => "tl",
    "tha" => "th",
    "tib" => "bo",
    "tir" => "ti",
    "ton" => "to",
    "tsn" => "tn",
    "tso" => "ts",
    "tuk" => "tk",
    "tur" => "tr",
    "twi" => "tw",
    "uig" => "ug",
    "ukr" => "uk",
    "urd" => "ur",
    "uzb" => "uz",
    "ven" => "ve",
    "vie" => "vi",
    "vol" => "vo",
    "wel" => "cy",
    "wln" => "wa",
    "wol" => "wo",
    "xho" => "xh",
    "yid" => "yi",
    "yor" => "yo",
    "zha" => "za",
    "zul" => "zu",
  ];
  if (strlen($lang) == 3 && isset($map[$lang])) {
    return $map[$lang];
  }
  return 'en';
}
